### PR TITLE
get tests to compile and run with 2.13.0-M4

### PR DESCRIPTION
**Pull request by pjfanning**
I was able to get your branch to compile and pass tests using these changes.
Still need to work out how to get the commented out tests and the stream test to work

### CODE REVIEW

**Comment by nbauernfeind** [comment]
I'm getting ridiculous errors like these:
```
[error] /Users/nate/code/jackson/jackson-module-scala/src/test/scala/UnpackagedTest.scala:13:12: could not find implicit value for parameter pos: org.scalactic.source.Position
[error]   behavior of "DefaultScalaModule"
[error]            ^
[error] /Users/nate/code/jackson/jackson-module-scala/src/test/scala/UnpackagedTest.scala:17:12: value should is not a member of String
[error]     result should be ("""{"intValue":1,"stringValue":"foo"}""")
```

Did you not?

**Comment by nbauernfeind** [comment]
BTW, those tests fail because the containers have been more-or-less removed from Scala. The cast class exceptions are because the module doesn't know how to build the typedef'd types and builds a generic Iterable[] instead. It's probably better to throw a "Serialization Container Not Found" sort of exception.

**Comment by pjfanning** [comment]
I'm able to build and run the scala tests from command line using sbt

**Comment by nbauernfeind** [comment]
Not sure if it makes a difference... but with which jdk?

**Comment by nbauernfeind** [comment]
NM! It works with jdk 8. It fails to compile with jdk 10.

**Comment by nbauernfeind** [comment]
Closing because I can actually address most of these. Thanks for the help.

**Pull request closed without merging**
